TASK-49227 : manage my wallet password"
Meeds-io/wallet pull request #119
Opened 2021-10-08 16:36 UTC by GouadriaHanen

2021-10-08 22:23 UTC, plamarque commented on wallet-services/src/main/resources/locale/addon/Wallet_en.properties
> +exoplatform.wallet.message.managePassword=You'll have to input your existing password
```suggestion
exoplatform.wallet.message.managePassword=You'll have to enter your existing password
```

2021-10-12 13:23 UTC, Rdidmohamedelhadi requested changes

2021-10-12 13:23 UTC, Rdidmohamedelhadi commented on wallet-webapps-common/src/main/webapp/vue-app/components/WalletBrowserSetup.vue
> +      return saveBrowserWalletInstance(wallet[0], this.walletPassword, this.isSpace,true)
```suggestion
      return saveBrowserWalletInstance(wallet[0], this.walletPassword, this.isSpace, true)
```

2021-10-12 13:23 UTC, Rdidmohamedelhadi commented on wallet-webapps-common/src/main/webapp/vue-app/components/WalletResetModal.vue
> +        right
change the name of this file to WalletResetDrawer instead of WalletResetModel

2021-10-12 13:23 UTC, Rdidmohamedelhadi commented on wallet-webapps-common/src/main/webapp/vue-app/components/WalletResetModal.vue
> +    },
```suggestion
    isSpace: {
      type: Boolean,
      default: false,
    },
```

2021-10-12 13:23 UTC, Rdidmohamedelhadi commented on wallet-webapps-common/src/main/webapp/vue-app/wallet-settings/components/WalletSettingsDetails.vue
> +      return this.wallet.spaceId !== 0;
check if this.wallet.spaceId is null

2021-10-12 14:05 UTC, Rdidmohamedelhadi requested changes
Please change This

2021-10-12 14:05 UTC, Rdidmohamedelhadi commented on wallet-webapps-common/src/main/webapp/vue-app/components/WalletPasswordManagement.vue
> +import {sendPrivateKeyToServer} from '../js/WalletUtils.js';
```suggestion
import {unlockBrowserWallet, saveBrowserWallet, hashCode, rememberPassword, sendPrivateKeyToServer} from '../js/WalletUtils.js';
```

2021-10-12 14:20 UTC, Rdidmohamedelhadi approved these changes
LGTM

2021-10-12 14:29 UTC, merged