Task-49860 : Re-font welcome message in wallet
Meeds-io/wallet pull request #131
Opened 2021-10-28 11:04 UTC by Rdidmohamedelhadi

I changed the welcome message in the wallet to be clearer than the old message

2021-11-01 09:25 UTC, ahamdi requested changes

2021-11-01 09:25 UTC, ahamdi commented on wallet-services/src/main/resources/locale/addon/Wallet_en.properties
> +exoplatform.wallet.label.createWalletInvitation.lastDescription=2- to define a wallet password which will be needed in different transactions.
Let's use numbered bullets for displaying those elements.

2021-11-01 14:45 UTC, Rdidmohamedelhadi commented on wallet-services/src/main/resources/locale/addon/Wallet_en.properties
> +exoplatform.wallet.label.createWalletInvitation.lastDescription=2- to define a wallet password which will be needed in different transactions.
done !

2021-11-02 21:14 UTC, ahamdi reviewed
Could you add a description to the PR following the PR templates

2021-11-05 20:08 UTC, ahamdi approved these changes

2021-11-05 20:08 UTC, merged