TASK-50881: fixed wallet widget redirection
Meeds-io/wallet pull request #138
Opened 2021-11-04 11:42 UTC by GouadriaHanen

on clicking on the wallet widget  it redirects to "dw/Wallet"
which is erroneous for the meeds site since it was statically created 
fixed by making the URL dynamically

2021-11-04 20:50 UTC, ahamdi requested changes

2021-11-04 20:50 UTC, ahamdi commented on wallet-webapps/src/main/webapp/WEB-INF/jsp/walletBalance.jsp
> +    walletUrl = "/portal/" + requestContext.getPortalOwner() + "/wallet";
Could you use `org.exoplatform.social.core.service.LinkProvider#getPortalName` to replace the string *portal* too

2021-11-05 13:09 UTC, GouadriaHanen commented
related PR
https://github.com/Meeds-io/social/pull/1063

2021-11-08 09:14 UTC, GouadriaHanen commented
related PR : https://github.com/Meeds-io/social/pull/1063

2021-11-08 13:47 UTC, ahamdi approved these changes

2021-11-08 13:47 UTC, merged