TASK-45348: Wallet view
Meeds-io/wallet pull request #51
Opened 2021-06-23 16:26 UTC by GouadriaHanen

2021-06-24 16:30 UTC, ahamdi requested changes

2021-06-24 16:30 UTC, ahamdi commented on wallet-webapps-common/src/main/webapp/css/main.less
> +    margin-left: 5% ;
take care of RTLisation

2021-06-24 16:30 UTC, ahamdi commented on wallet-webapps-common/src/main/webapp/css/main.less
> +        margin-left : 1%;
Take care of RTLisation

2021-06-24 17:40 UTC, GouadriaHanen commented on wallet-webapps-common/src/main/webapp/css/main.less
> +    margin-left: 5% ;
done!

2021-06-24 17:40 UTC, GouadriaHanen commented on wallet-webapps-common/src/main/webapp/css/main.less
> +        margin-left : 1%;
done!

2021-06-25 10:54 UTC, ahamdi approved these changes

2021-06-25 10:56 UTC, merged